server:
  port: 8085

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://localhost:8080
          predicates:
            - Path=/user/**, /users/**
        - id: emlakburada-banner
          uri: http://localhost:8081
          predicates:
            - Path=/banners/**
            - Method=POST,GET
        - id: emlakburada-auth
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**
            - Method=POST

  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive